// This file was autogenerated by ../closure-primitives/depswriter.py.
// Please do not edit.
goog.addDependency('../closure-primitives/base.js', ['goog'], []);
goog.addDependency('../src/midi_event.js', ['Midi.Event'], ['Typedef']);
goog.addDependency('../src/mld.js', ['Mld.Parser'], ['Typedef']);
goog.addDependency('../src/player.js', ['SMF.Player'], ['Mld.Parser', 'SMF.Parser']);
goog.addDependency('../src/riff.js', ['Riff.Parser'], ['Typedef']);
goog.addDependency('../src/smf.js', ['SMF.Parser'], ['Midi.Event', 'Riff.Parser', 'Typedef']);
goog.addDependency('../src/typedef.js', ['Typedef'], []);
